import { StyleSheet } from "react-native";
export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "hsl(205, 77%, 27%)",
    alignItems: "center",
    justifyContent: "flex-start",
  },
  title: {
    color: "hsl(205, 90%, 88%)",
    fontSize: 30,
    fontStyle: "italic",
    fontWeight: "400",
    textAlign: "center",
    marginBottom: 20,
  },
  searchbox: {
    fontSize: 20,
    fontWeight: "300",
    padding: 20,
    width: "90%",
    backgroundColor: "#fff",
    borderRadius: 8,
    marginBottom: 40,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 10,
    },
    shadowOpacity: 0.51,
    shadowRadius: 13.16,

    elevation: 20,
  },
  result: {
    flex: 1,
    width: "100%",
    marginBottom: 20,
  },
  heading: {
    color: "#fff",
    fontSize: 18,
    fontWeight: "700",
    padding: 20,
    backgroundColor: "#445565",
  },
  popup: {
    padding: 15,
    // backgroundColor: "#22254b",
  },
  movietitle: {
    fontSize: 30,
    fontWeight: "700",
    margin: 10,
    textAlign: "center",
  },
  closebtn: {
    color: "#fff",
    padding: 10,
    fontSize: 20,
    fontWeight: "700",
    backgroundColor: "#2484C4",
    marginRight: 90,
    marginLeft: 90,
    textAlign: "center",
  },
  loadMoreBtn: {
    padding: 10,
    backgroundColor: "#800000",
    borderRadius: 4,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    margin: 35,
  },
  btnText: {
    color: "white",
    fontSize: 15,
    textAlign: "center",
  },
  similarstyle: {
    margin: 10,
    color: "white",
    backgroundColor: "#445565",
    fontSize: 20,
    padding: 10,
    textAlign: "center",
    fontWeight: "700",
  },
});
